-- MySQL Script generated by MySQL Workbench
-- Tue Feb 26 19:29:48 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Club
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Club
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Club` DEFAULT CHARACTER SET utf8 ;
USE `Club` ;

-- -----------------------------------------------------
-- Table `Club`.`categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Club`.`categorie` ;

CREATE TABLE IF NOT EXISTS `Club`.`categorie` (
  `id` INT NOT NULL,
  `parentId` INT NULL,
  `name` VARCHAR(500) NULL,
  `description` VARCHAR(5000) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Club`.`member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Club`.`member` ;

CREATE TABLE IF NOT EXISTS `Club`.`member` (
  `id` INT NOT NULL,
  `categorieId` INT NULL,
  `description` VARCHAR(5000) NULL,
  `adressline` VARCHAR(5000) NULL,
  `surname` VARCHAR(500) NULL,
  `firstname` VARCHAR(500) NULL,
  `postalcode` VARCHAR(20) NULL,
  `place` VARCHAR(45) NULL,
  `licenceNumber` VARCHAR(500) NULL,
  `birthdate` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `cat_mem_idx` (`categorieId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Club`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Club`.`users` ;

CREATE TABLE IF NOT EXISTS `Club`.`users` (
  `id` INT NOT NULL,
  `username` VARCHAR(500) NULL,
  `password` VARCHAR(1000) NULL,
  `resetLink` VARCHAR(500) NULL,
  `resetTime` DATETIME NULL,
  `emailadress` VARCHAR(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Club`.`memberCategorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Club`.`memberCategorie` ;

CREATE TABLE IF NOT EXISTS `Club`.`memberCategorie` (
  `id` INT NOT NULL,
  `description` VARCHAR(5000) NULL,
  `name` VARCHAR(5000) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Club`.`member_categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Club`.`member_categorie` ;

CREATE TABLE IF NOT EXISTS `Club`.`member_categorie` (
  `id` INT NOT NULL,
  `memberId` INT NULL,
  `memberCategorieId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `mem_memcat_idx` (`memberId` ASC),
  INDEX `memcat_mem_idx` (`memberCategorieId` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
